spring:
  config:
    import: optional:file:.env[.properties]
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}
    driver-class-name: org.postgresql.Driver